version: '3.8'
services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./config/settings.yml:/app/config/settings.yml:ro
      - ./db:/app/db
      - ./log:/app/log
      - ${MUSIC_PATH:-/home/radio/content/music}:/home/radio/content/music:ro

