source 'https://rubygems.org'

gem 'telegram-bot-ruby', '~> 2'
gem 'activerecord', '~> 7.2'
gem 'activesupport', '~> 7.2'
gem 'i18n'
gem 'sqlite3', '~> 2.9'
gem 'unicode_utils'
gem 'translit'
gem 'google-search'
gem 'rest-client'
gem 'sk_google_custom_search_api', '~> 2.0.1'
gem 'nokogiri'
gem 'daemons'
gem 'pry'
gem 'faraday'
gem 'socksify'
#gem 'giphy'
gem 'aws-sdk-polly'
gem 'google_search_results', '~> 0.0.1'
gem 'httparty', '~> 0.24'
gem 'rss'
gem 'mutex_m'
gem 'ostruct'
gem 'base64'
gem 'benchmark'
gem 'logger'
gem 'csv'
gem 'observer'
gem 'rake'
gem 'wahwah'
gem 'numo-narray-alt'

group :development do
  gem 'irb', require: false
end
