source 'https://rubygems.org'

gem 'telegram-bot-ruby', '~> 2'
gem 'activerecord', '~> 6.0'
gem 'activesupport', '~> 6.0'
gem 'i18n'
gem 'sqlite3', '~> 1.4'
gem 'unicode_utils'
gem 'translit'
gem 'google-search'
gem 'rest-client'
gem 'sk_google_custom_search_api', '~> 2.0.1'
gem 'nokogiri'
gem 'daemons'
gem 'pry'
gem 'faraday'
#gem 'faraday_adapter_socks'
gem 'marky_markov'
#gem 'giphy'
gem 'aws-sdk-polly'
gem 'google_search_results', '~> 0.0.1'
gem 'httparty', '~> 0.18.1'
gem 'rss'
gem 'mutex_m'
gem 'ostruct'
gem 'base64'
gem 'benchmark'
gem 'logger'
gem 'csv'
gem 'observer'

group :development do
  gem 'irb', require: false
end
