source 'https://rubygems.org'

gem 'telegram-bot-ruby'
gem 'activerecord', '~> 4.0'
gem 'activesupport', '~> 4.0'
gem 'i18n'
gem 'sqlite3'
gem 'unicode_utils'
gem 'translit'
gem 'google-search'
gem 'rest-client'
gem 'sk_google_custom_search_api', '~> 2.0.1'
gem 'nokogiri'
gem 'daemons'
gem 'pry'
gem 'faraday'
gem 'ruby-filemagic'
gem 'marky_markov'
gem 'giphy'
