---
'евре(й|и|я|ев)|^жидо|^жыд':
  rate: 100
  answers:
    - "В еврейской сказке Ребе Гуд отбирал деньги у богатых и раздавал их бедным, под небольшой процент."
    - Настоящий еврей и пингвину в Антарктиде снег продаст.
    - "Изя, куда ты поедешь отдыхать в этом году?\n— Если Абрам отдаст деньги, то к морю.\n— А если не отдаст?\n— Тогда к Абраму."
    - "Мальчик Яша пришёл с папой в гости к тёте Песе. Та говорит:  — Подставь ладошку, я тебе орехов насыплю.  — Нет, лучше папе насыпьте.  — Ты что, не любишь орехов?  — Люблю, но у папы ладонь больше."
    - "Циля, где вы пропали?! Я же переживаю! А вдруг у вас всё хорошо..."
    - "Одесса. Дерибасовская.  — Сарочка, ты слышала последнюю речь Парашенки?  — Ой, не радуйте меня! Шо, таки последняя?!"
    - "Муж и жена насмотрелись эротического кино. — Сара, а почему ты не кричишь в постели? Давай ты будешь кричать. — Ну хорошо. Легли. Сара: — Уже кричать? – Нет, еще подожди. – Ну а теперь? – Еще рано. – А сейчас? – Давай кричи! – Ой, мене нету денег! Ой, мене дети не кормлены!"
    - "И привёл Бог с помощью Моисея еврейский народ в пустыню и сказал им:  — Может хоть здесь вы зла никому не причините!"
    - "— Сарочка! Ты пойдёшь в туалет?  — Нет!  — Тогда я смываю!"
    - "- Тётя Сара, ваш Абраша кушает кошачьи какашки! Тётя кричит в окно: - Абраша, не кушай много, скоро обед!"
    - "- Скажите, сколько стоят номера в вашем отеле?\n- На первом этаже - 60 евро, на втором - 50, на третьем - 40, на четвертом - 30.\n- Нет, спасибо, ваш отель недостаточно высок для меня."
    - "Хоп—хей—ла—ла—лей, все, мой мальчик, ты еврей!"
    - "Чем бендеровец отличается от еврея? У бендеровца обрез - на боку."
    - "— Сарочка, вы таки излишне опекаете своего сына. — Таки Сара Коннор как—нибудь сама разберется."
    - "Встречается еврейская молодежь, хвастается обновками. — Смотрите, какие у Мони часы! Где взял? — Отец перед смертью продал."
    - "Новый год в еврейском детском саду. ДЕД МОГОЗ: - Здгавсвуйте дети! Так, быстгее все подходим, покупаем себе подагки..."
    - "Скажите, ребе, а в субботу с парашютом прыгать можно? - Прыгать можно, но парашют открывать нельзя."
    - "Идут два еврея на свадьбу. Оба с конвертами. Первый спрашивает второго: — А сколько вы в конверт положили? Второй: — А что, по вашему конверт ничего не стоит?"
    - "Изя, а шо, правда, шо ты бандитам отдал всё золото и деньги??? — Таки да... Они вставили в зад паяльник, а на пузо утюг, и подключили к току!!!  — И ты сразу отдал??? — А шо, ждать пока за свет накрутит???"
    - "Умер старый богатый еврей. Вся семья собралась у нотариуса, чтобы узнать завещание. Нотариус читает: Я, Лахман Исаак Давидович, находясь в здравом уме и твердой памяти, все деньги потратил перед смертью."
    - "В чём разница между евреями и бойскаутами? Бойскауты возвращаются из своих лагерей."
    - "Еврейский ДЕД МОГОЗ приходит с кудрявой бородой, забирает у детей подарки и отдаёт стишки. Если он приходит, как русский – с перегаром, то уносит ещё два литра перегара с собой. Иногда еврейский Дед Мороз поздравляет детей по телефону или телеграммой. Но чаще всего он сидит дома, и все приходят к нему."
