---
'(–∞*—Ö+–∞+){2,}':
  rate: 50
  answers:
    - üòÇüòÇüòÇ
    - üòÜüòÜ
'^–¥–∞$':
  rate: 50
  answers:
    - –ø–∏–∑–¥–∞!
    - –î–∂–∏–≥—É—Ä–¥–∞!
    - —Ç–µ–±—è —Ç—Ä–∞—Ö–Ω—É–ª –î–∂–∏–≥—É—Ä–¥–∞!
    - —Ö—É–π –ø–∏–∑–¥–∞ —Å–∫–æ–≤–æ—Ä–æ–¥–∞!
'–ø–æ–Ω–∏$':
  rate: 50
  answers:
    - –æ–ø—è—Ç—å —Ç—ã –±–ª—è—Ç—å –ø—Ä–æ –ø–æ–Ω–∏!
'(\s+|^)–Ω–µ—Ç$':
  rate: 50
  answers:
    - –ø–∏–¥–æ—Ä–∞ –æ—Ç–≤–µ—Ç!
'(\s+|^)–≥–¥–µ((,|\s).*)*\?':
  - –≤ –ø–∏–∑–¥–µ!
  - –≤ –ì–∞—Ä–≤–∞—Ä–¥–µ!
  - —É –∫–∏–∂—É—á–∞ –≤ –≥–æ–ª–æ–≤–µ
  - —É –±–æ–±—Ä–∞ –≤ –∫–∞–Ω–¥–∏–±–æ–±–µ—Ä–µ
  - —É –ø–æ–Ω–µ–π –Ω–∞ –∫—Ä—É–ø–µ
'^—á—Ç–æ$':
  - "–∏–º–µ–Ω–Ω–æ —Ç–∞–∫ —Å–∫–∞–∑–∞–ª–∞ —Ç–≤–æ—è –º–∞–º–∫–∞, –∫–æ–≥–¥–∞ —Ç—ã —Ä–æ–¥–∏–ª—Å—è"
  - "—ç—Ç–æ –ø—Ä–æ—Å—Ç–æ —à—É–º—ã –ú—ã—Ç–∏—â"
  - "—É –º–∞–º–∫–∏ —Å–ø—Ä–æ—Å–∏"
  - "—á—Ç–æ"
'^—Ç—Ä–∏—Å—Ç–∞$':
  - "–æ—Ç—Å–æ—Å–∏ —É —Ç—Ä–∞–∫—Ç–æ—Ä–∏—Å—Ç–∞"
  - "–∫—Ä–∏–≤–æ—Ä—É–∫–∞—è –±–∞—Ä–∏—Å—Ç–∞"
  - "–∂–æ–ø–∞ –≥—Ä–∞—Ñ–∞ –ú–æ–Ω—Ç–µ-–ö—Ä–∏—Å—Ç–æ"
  - "–¥–Ω–µ–≤–Ω–∏–∫–∏ —ç–∫–≤–∏–ª–∏–±—Ä–∏—Å—Ç–∞"
  - "—Ñ–ª—É–∫—Ç—É–∞—Ü–∏–∏ –±–∞—Å–∏—Å—Ç–∞"
'–≥–µ–π$':
  - "—Ç–≤–æ—è –º–∞–º–∞ –≥–µ–π!"
  - "—Ç–≤–æ—è —Å–µ—Å—Ç—Ä–∞ –≥–µ–π!"
  - "–±—Ä–∞–¥–æ–±—Ä–µ–π-–±—Ä–∞–¥–æ–±—Ä–µ–π –±—É–¥—å —Å–æ –º–Ω–æ–π –ø–æ–¥–æ–±—Ä–µ–π"
  - —Å–∞–º –µ–±–∏ –ø–æ–Ω–µ–π
'–ø–∏–¥–æ—Ä$':
  - –ì–∞–∑–µ–ª—å –õ—É–∏–¥–æ—Ä
'(\s+|^)–∫—Ç–æ\s+–ª—É—á—à–µ\s+–≤—Å–µ—Ö.*':
  - –∫–æ–Ω–µ—á–Ω–æ, –í–∞—Å—è!
'(\s+|^)–∫—Ç–æ(\?|\s.*\?)':
  - —Ö—É–π –≤ –ø–∞–ª—å—Ç–æ!
  - –∫–∏–∂—É—á
'–∫–∏–∂—É—á':
  rate: 50
  answers:
    - "–≤–æ—Ç –æ–Ω–∞, —Ä—ã–±–∞ –º–æ–µ–π –º–µ—á—Ç—ã!"
    - "–ö–∏–∂—É—á ‚Äì –ª–æ—Å–æ—Å—å —Ç–∏—Ö–æ–æ–∫–µ–∞–Ω—Å–∫–∏–π, –∏ –µ–≥–æ —Ä–∞–∑–º–µ—Ä—ã - –æ–∫–æ–ª–æ –º–µ—Ç—Ä–∞ –¥–ª–∏–Ω–æ–π –∏ 14-15 –∫–≥ –≤–µ—Å–æ–º"
    - "–ö–∏–∂—É—á –æ—á–µ–Ω—å –ø–æ–ª–µ–∑–µ–Ω –≤—Å–µ–º, –æ—Å–æ–±–µ–Ω–Ω–æ –¥–µ—Ç—è–º, –±–µ—Ä–µ–º–µ–Ω–Ω—ã–º –∂–µ–Ω—â–∏–Ω–∞–º –∏ –ø–æ–∂–∏–ª—ã–º –ª—é–¥—è–º. –ú—è—Å–æ –µ–≥–æ –æ—á–µ–Ω—å –Ω–µ–∂–Ω–æ–µ."
    - "–ö–∞–ª–æ—Ä–∏–π–Ω–æ—Å—Ç—å —Ä—ã–±—ã –∫–∏–∂—É—á 140 –∫–∫–∞–ª/100–≥—Ä, –≤—ã—Å–æ–∫–æ–µ —Å–æ–¥–µ—Ä–∂–∞–Ω–∏–µ –±–µ–ª–∫–∞, –∞ —É–≥–ª–µ–≤–æ–¥–æ–≤ –≤ –Ω–µ–º –Ω–µ—Ç —Å–æ–≤—Å–µ–º. –≠—Ç–∞ –ø–æ–ª–µ–∑–Ω–∞—è —Ä—ã–±–∫–∞ –≤—Ö–æ–¥–∏—Ç –≤ —Å–µ–º–µ–π—Å—Ç–≤–æ –ª–æ—Å–æ—Å–µ–≤—ã—Ö, –Ω–æ –Ω–µ –æ—Ç–ª–∏—á–∞–µ—Ç—Å—è –±–æ–ª—å—à–∏–º —Ä–∞–∑–º–µ—Ä–æ–º."
'(\s+|^)(–≥–∏—Ç–ª–µ—Ä)|(–∑–∏–≥(–∞–Ω–∏|—É))':
  - "o/"
  - "O/"
  - "√î/"
  - "√ï/"
  - "√ò/"
  - "√∞/"
  - "≈ê/"
  - "≈í/"
  - "∆ü/"
  - "«ë/"
  - "«¨/"
  - "«æ/"
  - "»¨/"
'^([[:word:]]{1}\/|\\[[:word:]]{1})$':
  rate: 80
  answers:
    - "o/"
    - "O/"
    - "√î/"
    - "√ï/"
    - "√ò/"
    - "√∞/"
    - "≈ê/"
    - "≈í/"
    - "∆ü/"
    - "«ë/"
    - "«¨/"
    - "«æ/"
    - "»¨/"
'–ø—å—è–Ω—ã–π[,]?\s(—á—Ç–æ\s?–ª–∏|—à—Ç–æ–ª–µ)':
  - —è –±—ã –µ—â–µ –≤—ã–ø–∏–ª!
  - "–º–Ω–µ –Ω—É–∂–Ω–æ –≤—ã–ø–∏—Ç—å, —á—Ç–æ–±—ã —Å–µ—Å—Ç—å –∑–∞ —Ä—É–ª—å!"
'(\s+|^)–≥–ª–∞–∑\W':
  - –ì–ª–∞–∑ –∂–∏–≤—ë—Ç –≤ –ì–ª–∞–∑–≥–æ. –ù–∞ —É–ª–∏—Ü–µ –ì–ª–∞–∑–Ω–æ–π.
  - –ì–ª–∞–∑ –≤–∏–¥–µ–ª –≤–∞—Å.
  - '–ì–ª–∞–∑ –Ω–∞—Å–º–æ—Ç—Ä–µ–ª—Å—è, –Ω–∞–≥–ª–∞–∑–µ–ª—Å—è.'
'(^|\s+|[^—Åc])—Ç—Ä–∞—Ö–∞?(—Ç|–ª|–µ|—é)?':
  rate: 50
  answers:
    - "–ø–æ–≥–ª–∞–∑–µ—Ç—å –±—ã‚Ä¶"
    - "–Ω–∏–∫—Ç–æ –µ–º—É –Ω–µ –¥–∞—Å—Ç, –ø—É—Å—Ç—å –Ω–µ –ø–∏–∑–¥–∏—Ç"
'—Å–¥–µ–ª–∞–π(—Ç–µ)?\s—á—Ç–æ-–Ω–∏–±—É–¥—å':
  - —É–∂–µ —Å–¥–µ–ª–∞–ª
  - "–î–µ–ª–∞—é, –¥–µ–ª–∞–ª‚Ä¶ –£–∂–µ –≥–æ—Ç–æ–≤–æ!"
'(\s+|^)–Ω–æ—á—å':
  rate: 50
  answers:
    - "–ù–æ—á—å‚Ä¶ –û–Ω–∞ —Ç–∞–∫–∞—è‚Ä¶ –Ω–æ—á–Ω–∞—è."
'—Ñ–æ—Ä–º—É–ª–∞':
  - "–ß—Ç–æ —ç—Ç–æ? –ß—Ç–æ –∑–∞ —Ñ–æ—Ä–º—É–ª—ã? –ë—É–º–∞–≥–∏‚Ä¶ –ë—É–º–∞–≥–∏ —Å–≤–æ–¥—è—Ç —Å —É–º–∞. –°–≤–æ–¥—è—Ç —Å —É–º–∞ –∏ –º–∞–Ω—è—Ç –≤ –Ω–æ—á—å."
'(\s+|^)—Ö–æ—á—É\s(–µ—Å—Ç—å|–∂—Ä–∞—Ç—å)':
  rate: 50
  answers:
    - "–Ø —Ç–æ–∂–µ –µ—Å—Ç—å —Ö–æ—á—É. –ù–æ –≤ —Ö–æ–ª–æ–¥–∏–ª—å–Ω–∏–∫–µ —Ç–æ–ª—å–∫–æ —Ä—É–∫–∞ –∏ —Ö–æ–ª–æ–¥–Ω—ã–π —Ç–µ–ª–µ—Ñ–æ–Ω –≤ –º–æ—Ä–æ–∑–∏–ª–∫–µ"
'–º–æ–ª–µ–∫—É–ª–∞':
  - –ê–ß–ò–õ–ê–í–ï–ö–ú–ê–õ–ï–ö–£–õ–ê!!11
  - –ú–û–õ–ï–ö–£–õ–Ø–†–ù–´–ô –î–Ø–î–¨–ö–û!!11
'–¥–µ–Ω—å–≥–∏':
  rate: 50
  answers:
    - –¥–µ–Ω—å–≥–∏-—à–º–µ–Ω—å–≥–∏
'(\s+|^)–≤–µ—Ä–Ω—É–ª—Å—è':
  rate: 50
  answers:
    - –≤–µ—Ä–Ω—É–ª—Å—è —Ä–∞–∑–≤–µ—Ä–Ω—É–ª—Å—è!
'(\s+|^)—Ü–µ–ª—É–π':
  - —Ç–∏—Å–∫–∞–π –µ—ë!
  - —Ö–≤–∞—Ç–∞–π –∑–∞ –∂–æ–ø—É!
  - —Å–∏—Å—å–∫–∏ –ø–æ–º–Ω–∏!
  - –∑–∏–≥—É–π
  - "–∞ —Ç—ã —á–æ, —Å–≤–µ—á–∫—É –¥–µ—Ä–∂–∞–ª?"
'^–º—ã—à—å':
  - "http://cs628725.vk.me/v628725122/3c17f/xHG2AzaIYtc.jpg"
  - "http://cs628725.vk.me/v628725122/3c194/61GN_zG0aUs.jpg"
  - "http://cs628725.vk.me/v628725122/3c194/61GN_zG0aUs.jpg"
'—á—Ç?–æ\s.*–¥–µ–ª–∞—Ç—å.*?':
  - —Å–≤–∏—Å—Ç–Ω–∏ –≤ —Ö—É–π
  - —Å–¥–µ–ª–∞–π —á—Ç–æ-–Ω–∏–±—É–¥—å
  - –∑–∞–≤–µ–¥–∏ –¥—Ä—É–∑–µ–π
  - –Ω–∞–π–¥–∏ —Ä–∞–±–æ—Ç—É
  - –µ–±–∏ –≥—É—Å–µ–π
  - –≤–æ—Ä—É–π —É–±–∏–≤–∞–π
  - –∑–∏–≥—É–π
  - –∂–¥–∏ –æ—Ç–≤–µ—Ç–Ω–æ–≥–æ –≥—É–¥–∫–∞
'–ø–æ—á–µ–º—É.*?':
  - –ø–æ –∫–æ—á–∞–Ω—É
  - –ø–æ—Ç–æ–º—É —á—Ç–æ –≥–ª–∞–¥–∏–æ–ª—É—Å
  - –ø–æ—Ç–æ–º—É —á—Ç–æ –∫–∞—Ä–º–∞ –ø–ª–æ—Ö–∞—è
  - –ø–æ—Ç–æ–º—É —á—Ç–æ —Ç—ã –º—É–¥–∞–∫
  - —ç—Ç–æ–≥–æ —Ç—ã –Ω–∏–∫–æ–≥–¥–∞ –Ω–µ —É–∑–Ω–∞–µ—à—å
'—É\s–º–µ–Ω—è\s–µ—Å—Ç—å':
  - "–Ω–∞–∫—Ä—É—Ç–∏ –µ–≥–æ –Ω–∞ —á–ª–µ–Ω"
'—Å–¥–µ–ª–∞—Ç—å':
  rate: 50
  answers:
    - "–Ω–∏—Ö—É—è —É —Ç–µ–±—è –Ω–µ –ø–æ–ª—É—á–∏—Ç—Å—è"
    - "–∞ —Ç—ã –≤–æ–∑—å–º–∏ –∏ —Å–¥–µ–ª–∞–π"
    - "–ø–∏–∑–¥–µ—Ç—å ‚Äî –Ω–µ –º–µ—à–∫–∏ –≤–æ—Ä–æ—á–∞—Ç—å"
'—Ç–≤–µ—Ä—å':
  - "–∑–∞–∫—Ä–æ–π –∑–∞ –º–Ω–æ–π —Ç–≤–µ—Ä—å, —è –º—É—Ö–æ–∂—É–∫"
  - "–¥–≤–µ—Ä—å –≤ —Ç–≤–µ—Ä—å"
  - "—Å–∞–º —Ç–≤–∞—Ä—å"
'–∂–∞–ª(–∫–æ|—å)':
  - –º–∞–º–∫–∞ –ø–æ–∂–∞–ª–µ–µ—Ç
  - –≤ –¥–µ—Ç—Å–∫–æ–º —Å–∞–¥–∏–∫–µ –ø–æ–∂–∞–ª–µ—é—Ç
  - –≤ —à–∫–æ–ª–µ —É—á–∏—Ç–µ–ª—å–Ω–∏—Ü–∞ –ø–æ–∂–∞–ª–µ–µ—Ç
  - –≤ –∏–Ω—Å—Ç–∏—Ç—É—Ç–µ –¥–µ–∫–∞–Ω –ø–æ–∂–∞–ª–µ–µ—Ç
  - –Ω–∞ —Ä–∞–±–æ—Ç–µ –¥–∏—Ä–µ–∫—Ç–æ—Ä –ø–æ–∂–∞–ª–µ–µ—Ç
'–≤–æ—Ç':
  rate: 20
  answers:
    - –æ–¥–Ω–∞ –∏—Å—Ç–æ—Ä–∏—è –æ—Ö—É–∏—Ç–µ–ª—å–Ω–µ–π –¥—Ä—É–≥–æ–π
'(—è+|–π+–∞+)–∑+—å+':
  - —è–∑—å –ø—Ä–æ–∏–≥—Ä—ã–≤–∞–µ—Ç –∫–∏–∂—É—á—É –≤—á–∏—Å—Ç—É—é
  - –∫–∏–∂—É—á—É —è–∑—å –Ω–µ —Ç–æ–≤–∞—Ä–∏—â—å
  - "–ô–ê-–ê-–ê-–ê-–ê-–ó–¨!!!"
  - "–ó–î–ê-–†–ê-–í–ï-–ù–ù–´–ô !!!111"
  - –ö–ò–ñ–£–ß–ß–ß!!!111
  - "–í–æ—Ç –æ–Ω–∞, —Ä—ã–±–∞ –º–æ–µ–π –º–µ—á—Ç—ã! –í–æ—Ç –æ–Ω–∞! –í–æ—Ç –æ–Ω–∞-–∞-–∞!!! –ô–ê-–ê-–ê-–ê-–ê-–ó–¨!"
  - "–†–µ–±—è—Ç–∞, —è–∑—å! –ó–¥–∞—Ä–∞–≤–µ–Ω–Ω—ã–π, –ó–î–ê-–†–ê-–í–ï-–ù–ù–´–ô –ô–ê-–ê-–ê–ó–¨! –ô–ê-–ê-–ê-–ê-–ê-–ó–¨!"
  - "–≠—Ö–æ –≥—É–ª—è–µ—Ç –ø–æ –Ø—Ö—Ä–µ–Ω—å–≥—Å–∫–æ–º—É –æ–∑–µ—Ä—É‚Ä¶ –ú–ê-–ú–ê-–ê-–ê-–ê-–ê!!!"
'–≤–∞—à–∏ –¥–æ–∫–∞–∑–∞—Ç–µ–ª—å—Å—Ç–≤–∞':
  - –ö–æ–∫–∞–∏–Ω—É–º!
  - –°–ò–ò–ò–õ–ê–ê–ê –õ–ï–ï–ï–ï–ë–ï–î–Ø–Ø–Ø–Ø–Ø!!

'—Ç—Ä—ç—à':
  rate: 20
  answers:
    - "https://pp.vk.me/c11449/u1408940/101828168/x_036a11c9.jpg"

'(\s+|^)—É–ø–∞–ª(–∏|–∞|–æ)?\W':
  answers:
    - "–£–ø–∞–ª ‚Äî –æ—Ç–∂–∞–ª—Å—è!"

track_not_found:
  - –Ω–∏—Ö—É—è –Ω–µ—Ç —ç—Ç–æ–≥–æ –≥–æ–≤–Ω–∞ —É –Ω–∞—Å
  - "–û—á–µ–≤–∏–¥–Ω–æ, —á—Ç–æ –ø—Å–∏—Ö–æ–∑ —Ä–∞—Å–∫–ª–∞–¥—ã–≤–∞–µ—Ç –Ω–∞ —ç–ª–µ–º–µ–Ω—Ç—ã –Ω–µ—Å–∏–º–º–µ—Ç—Ä–∏—á–Ω—ã–π –¥–∏–º–µ—Ä, –æ–¥–Ω–æ–∑–Ω–∞—á–Ω–æ —Å–≤–∏–¥–µ—Ç–µ–ª—å—Å—Ç–≤—É—è –æ –Ω–µ—É—Å—Ç–æ–π—á–∏–≤–æ—Å—Ç–∏ –ø—Ä–æ—Ü–µ—Å—Å–∞ –≤ —Ü–µ–ª–æ–º."
  - –ö–∞—Ç–æ–¥ –≤–∑–≤–µ—à–∏–≤–∞–µ—Ç —Ç–∞—Ö–∏–æ–Ω–Ω—ã–π –≥—Ä–∞–≤–∏—Ç–∞—Ü–∏–æ–Ω–Ω—ã–π –ø–∞—Ä–∞–¥–æ–∫—Å
  - "–ï—â–µ –≤ —Ä–∞–Ω–Ω–∏—Ö —Ä–∞–±–æ—Ç–∞—Ö –õ.–î.–õ–∞–Ω–¥–∞—É –ø–æ–∫–∞–∑–∞–Ω–æ, —á—Ç–æ –∑–Ω–∞–∫ –º–µ—Ç–æ–¥–æ–ª–æ–≥–∏—á–µ—Å–∫–∏ –¥–∏—Å—Å–æ—Ü–∏–∏—Ä—É–µ—Ç —ç—Ç–∏–ª–æ–≤—ã–π –ª—É—á"
  - "–ê—Å—Å–æ—Ü–∏–∞–Ω–∏–∑–º, –Ω–µ—Å–º–æ—Ç—Ä—è –Ω–∞ –Ω–µ–∫–æ—Ç–æ—Ä—É—é –≤–µ—Ä–æ—è—Ç–Ω–æ—Å—Ç—å –∫–æ–ª–ª–∞–ø—Å–∞, –¥–µ–≥–∏–¥—Ä–∏—Ä–æ–≤–∞–Ω"
  - "–ó–¥–µ—Å—å –Ω–∏—á–µ–≥–æ –Ω–µ—Ç –∏ –Ω–µ –±—É–¥–µ—Ç"
  - "–ù–µ –µ—à—å –≤–∞—Ä–µ–Ω—å–µ, –µ—à—å –ø–µ—á–µ–Ω—å–µ!"
  - "–ì–µ—Ç–µ—Ä–æ–≥–µ–Ω–Ω—ã–π –≤—ã—Ö–æ–¥ —Ü–µ–ª–µ–≤–æ–≥–æ –ø—Ä–æ–¥—É–∫—Ç–∞ ‚Äî –∫–æ–ª–µ–±–∞–Ω–∏–µ –∏–ª–∏ —É—Ä–∞–≤–Ω–µ–Ω–∏–µ?"
  - "–í–∞—à –∑–∞–∫–∞–∑ –æ—Ñ–æ—Ä–º–ª–µ–Ω –Ω–µ–≤–µ—Ä–Ω–æ, –∑–∞–ø–æ–ª–Ω–∏—Ç–µ —Ñ–æ—Ä–º—É 69"
