---
'(а*х+а+){2,}':
  rate: 50
  answers:
    - 😂😂😂
    - 😆😆
'^да$':
  rate: 50
  answers:
    - пизда!
    - Джигурда!
    - тебя трахнул Джигурда!
    - хуй пизда сковорода!
'пони$':
  rate: 50
  answers:
    - опять ты блять про пони!
'(\s+|^)нет$':
  rate: 50
  answers:
    - пидора ответ!
'(\s+|^)где((,|\s).*)*\?':
  - в пизде!
  - в Гарварде!
  - у кижуча в голове
  - у бобра в кандибобере
  - у поней на крупе
'^что$':
  - "именно так сказала твоя мамка, когда ты родился"
  - "это просто шумы Мытищ"
  - "у мамки спроси"
  - "что"
'^триста$':
  - "отсоси у тракториста"
  - "криворукая бариста"
  - "жопа графа Монте-Кристо"
  - "дневники эквилибриста"
  - "флуктуации басиста"
'гей$':
  - "твоя мама гей!"
  - "твоя сестра гей!"
  - "брадобрей-брадобрей будь со мной подобрей"
  - сам еби поней
'пидор$':
  - Газель Луидор
'(\s+|^)кто\s+лучше\s+всех.*':
  - конечно, Вася!
'(\s+|^)кто(\?|\s.*\?)':
  - хуй в пальто!
  - кижуч
'кижуч':
  rate: 50
  answers:
    - "вот она, рыба моей мечты!"
    - "Кижуч – лосось тихоокеанский, и его размеры - около метра длиной и 14-15 кг весом"
    - "Кижуч очень полезен всем, особенно детям, беременным женщинам и пожилым людям. Мясо его очень нежное."
    - "Калорийность рыбы кижуч 140 ккал/100гр, высокое содержание белка, а углеводов в нем нет совсем. Эта полезная рыбка входит в семейство лососевых, но не отличается большим размером."
'(\s+|^)(гитлер)|(зиг(ани|у))':
  - "o/"
  - "O/"
  - "Ô/"
  - "Õ/"
  - "Ø/"
  - "ð/"
  - "Ő/"
  - "Œ/"
  - "Ɵ/"
  - "Ǒ/"
  - "Ǭ/"
  - "Ǿ/"
  - "Ȭ/"
'^([[:word:]]{1}\/|\\[[:word:]]{1})$':
  rate: 80
  answers:
    - "o/"
    - "O/"
    - "Ô/"
    - "Õ/"
    - "Ø/"
    - "ð/"
    - "Ő/"
    - "Œ/"
    - "Ɵ/"
    - "Ǒ/"
    - "Ǭ/"
    - "Ǿ/"
    - "Ȭ/"
'пьяный[,]?\s(что\s?ли|штоле)':
  - я бы еще выпил!
  - "мне нужно выпить, чтобы сесть за руль!"
'(\s+|^)глаз\W':
  - Глаз живёт в Глазго. На улице Глазной.
  - Глаз видел вас.
  - 'Глаз насмотрелся, наглазелся.'
'(^|\s+|[^сc])траха?(т|л|е|ю)?':
  rate: 50
  answers:
    - "поглазеть бы…"
    - "никто ему не даст, пусть не пиздит"
'сделай(те)?\sчто-нибудь':
  - уже сделал
  - "Делаю, делал… Уже готово!"
'(\s+|^)ночь':
  rate: 50
  answers:
    - "Ночь… Она такая… ночная."
'формула':
  - "Что это? Что за формулы? Бумаги… Бумаги сводят с ума. Сводят с ума и манят в ночь."
'(\s+|^)хочу\s(есть|жрать)':
  rate: 50
  answers:
    - "Я тоже есть хочу. Но в холодильнике только рука и холодный телефон в морозилке"
'молекула':
  - АЧИЛАВЕКМАЛЕКУЛА!!11
  - МОЛЕКУЛЯРНЫЙ ДЯДЬКО!!11
'деньги':
  rate: 50
  answers:
    - деньги-шменьги
'(\s+|^)вернулся':
  rate: 50
  answers:
    - вернулся развернулся!
'(\s+|^)целуй':
  - тискай её!
  - хватай за жопу!
  - сиськи помни!
  - зигуй
  - "а ты чо, свечку держал?"
'^мышь':
  - "мышь!"
  - "кто тут мышь?!"
  - "пойди мышь поймай"
'чт?о\s.*делать.*?':
  - свистни в хуй
  - сделай что-нибудь
  - заведи друзей
  - найди работу
  - еби гусей
  - воруй убивай
  - зигуй
  - жди ответного гудка
'почему.*?':
  - по кочану
  - потому что гладиолус
  - потому что карма плохая
  - потому что ты мудак
  - этого ты никогда не узнаешь
'у\sменя\sесть':
  - "накрути его на член"
'сделать':
  rate: 50
  answers:
    - "нихуя у тебя не получится"
    - "а ты возьми и сделай"
    - "пиздеть — не мешки ворочать"
'тверь':
  - "закрой за мной тверь, я мухожук"
  - "дверь в тверь"
  - "сам тварь"
'жал(ко|ь)':
  - мамка пожалеет
  - в детском садике пожалеют
  - в школе учительница пожалеет
  - в институте декан пожалеет
  - на работе директор пожалеет
'вот':
  rate: 20
  answers:
    - одна история охуительней другой
'(я+|й+а+)з+ь+':
  - язь проигрывает кижучу вчистую
  - кижучу язь не товарищь
  - "ЙА-А-А-А-А-ЗЬ!!!"
  - "ЗДА-РА-ВЕ-ННЫЙ !!!111"
  - КИЖУЧЧЧ!!!111
  - "Вот она, рыба моей мечты! Вот она! Вот она-а-а!!! ЙА-А-А-А-А-ЗЬ!"
  - "Ребята, язь! Здаравенный, ЗДА-РА-ВЕ-ННЫЙ ЙА-А-АЗЬ! ЙА-А-А-А-А-ЗЬ!"
  - "Эхо гуляет по Яхреньгскому озеру… МА-МА-А-А-А-А!!!"
'ваши доказательства':
  - Кокаинум!
  - СИИИЛААА ЛЕЕЕЕБЕДЯЯЯЯЯ!!

'трэш':
  rate: 20
  answers:
    - "трэш угар и содомия"

'(\s+|^)упал(и|а|о)?\W':
  - "Упал — отжался!"

track_not_found:
  - нихуя нет этого говна у нас
  - "Очевидно, что психоз раскладывает на элементы несимметричный димер, однозначно свидетельствуя о неустойчивости процесса в целом."
  - Катод взвешивает тахионный гравитационный парадокс
  - "Еще в ранних работах Л.Д.Ландау показано, что знак методологически диссоциирует этиловый луч"
  - "Ассоцианизм, несмотря на некоторую вероятность коллапса, дегидрирован"
  - "Здесь ничего нет и не будет"
  - "Не ешь варенье, ешь печенье!"
  - "Гетерогенный выход целевого продукта — колебание или уравнение?"
  - "Ваш заказ оформлен неверно, заполните форму 69"
