---
'(\s+|^)например':
  rate: 50
  answers:
    - например например например
    - 'как бодрость духа, например?'
    - 'атлична-атлична, больше угара!'
    - 'Почему «трэш, угар и содомия», например? Ну эта тащемта общечеловеческие ценности, например. Какие могут быть лучше, например?'
    - 'въеби моднейшего крымского портвейна например!'
    - 'Дело в том, что девушка всегда мечтает быть голой, например, да, и чтоб ее видело много людей например.'
    - 'рэп - это тащемта просто кал, например'
'(\s+|^)(бот|жзяцля).*как\s+бодрость\s+духа':
  - 'атлична-атлична, больше угара!'
