---
'(\s+|^)например':
  rate: 50
  answers:
    - например например например
    - 'как бодрость духа, например?'
    - 'атлична-атлична, больше угара!'
    - 'Почему «трэш, угар и содомия», например? Ну эта тащемта общечеловеческие ценности, например. Какие могут быть лучше, например?'
    - 'въеби моднейшего крымского портвейна например!'
    - 'Дело в том, что девушка всегда мечтает быть голой, например, да, и чтоб ее видело много людей например.'
    - 'рэп - это тащемта просто кал, например'
    - 'ээээээ, называется'
    - 'И, конечно, он... эээ... Кремль меня передвинул... эээ... на Арбат, где Любовь Соб... Собо-Соболь участвовала, называется... для того, что-чтобы... эээ...'
    - 'я тебе с... эээ... щас это все рассказать н-н-не могу, назвается... это нужно объяснять, ну, придем на пляж, я тебе... эээ... будем лежать и я тебе там...'
    - 'Моряк застрянет на корабле на какое-то большое время, у него крыша может съехать. А когда он вышел... эээ... на пристань, называется, он стусовался с проституткой, называется. Оттянулся, угорел, тарыбар-растабары, и снова на железную банку, называется, сел, сел, и... сел, и поп... поплыл.'
    - 'Нам... нам нужны нуу это, эээ... интеллектуальное творческие у-успехи, которые сделают всю политику России более... более солидной. Чтобы были писатели, ки-кино, тарыбар-растабары. Со мной был в камере один серб... эээ, вот... но он действительно знал Михалкова.'
'(\s+|^)(бот|жзяцля).*как\s+бодрость\s+духа':
  - 'атлична-атлична, больше угара!'
