module Commands
  # Order matters — first match wins
  REGISTRY = [
    TtsVoice,
    BoberVoice,
    OrderBlock,
    OrderRequest,
    RadioSearch,
    RadioTrack,
    Stats,
    RadioQueue,
    Weather,
    Listeners,
    RemoveTrack,
    Remaining,
    History,
    RadioTop,
    Meta,
    Help,
    KnowledgeAdd,
    KnowledgeList,
    KnowledgeDelete,
    KnowledgeCompact,
    Translate,
    News,
    Dice,
    PhraseTop,
    TaskQueue,
    CostReport,
    GptChat,
    FallbackReply,
  ].freeze
end
